# Write an algorithm that takes an integer and generates 
# the Collatz sequence for that number.

# The Collatz sequence is generated by applying the following rules:
# if the number is even, divie it by 2
# if the number is odd, multiply it by 3 and add 1
# Repeat this process until you reach the number 1.

# E.g. The Collatz squence for the number 6 is 6, 3, 10, 5, 16, 8, 4, 2, 1.
# More info: https://brainly.com/question/53133031 

def collatz_sequence(number):
  sequence = [number]
  while number != 1:
    if number % 2 == 0:
      number = number // 2
    else:
      number = number * 3 + 1
    sequence.append(number)
  return sequence


# Test the collatz_sequence function
print("The Collatz sequence:", collatz_sequence(6))